{{- define "library.secret" -}}
{{- if or .Values.secret.data .Values.secret.stringData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.secret.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.secret.annotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.secret.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.secret.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
type: {{ default "Opaque" .Values.secret.type }}
{{- if .Values.secret.data }}
data: {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData: {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}
