apiVersion: v2
name: test-consumer
description: Test consumer chart for naviteq-library-chart
type: application
version: 0.1.0
dependencies:
  - name: naviteq-library-chart
    version: ">=0.0.1"
    repository: "file://../chart"
    import-values:
      - defaults
