{{- define "library.statefulSet" -}}
---
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  serviceName: {{ default (include "common.names.fullname" .) .Values.statefulSet.serviceName }}
  {{- if .Values.statefulSet.podManagementPolicy }}
  podManagementPolicy: {{ .Values.statefulSet.podManagementPolicy }}
  {{- end }}
  {{- if .Values.statefulSet.minReadySeconds }}
  minReadySeconds: {{ .Values.statefulSet.minReadySeconds }}
  {{- end }}
  {{- if .Values.statefulSet.ordinals }}
  ordinals: {{- toYaml .Values.statefulSet.ordinals | nindent 4 }}
  {{- end }}
  {{- if .Values.statefulSet.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy: {{- toYaml .Values.statefulSet.persistentVolumeClaimRetentionPolicy | nindent 4 }}
  {{- end }}
  {{- if .Values.updateStrategy }}
  updateStrategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template: {{- include "library.podTemplate" (dict "context" $ "volumeClaimTemplates" .Values.statefulSet.volumeClaimTemplates) | nindent 4 }}
  {{- if .Values.statefulSet.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- range .Values.statefulSet.volumeClaimTemplates }}
    - metadata:
        name: {{ .metadata.name }}
        {{- if .metadata.labels }}
        labels: {{- toYaml .metadata.labels | nindent 10 }}
        {{- end }}
        {{- if .metadata.annotations }}
        annotations: {{- toYaml .metadata.annotations | nindent 10 }}
        {{- end }}
      spec: {{- toYaml .spec | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end -}}
