{{/*
Render ClusterPushSecret CRs from .Values.eso.clusterPushSecrets dict.
Cluster-scoped: no namespace in metadata.

apiVersion: external-secrets.io/v1alpha1
ref: https://external-secrets.io/latest/api/clusterpushsecret/
*/}}
{{- define "library.clusterPushSecrets" -}}
{{- range $name, $cps := .Values.eso.clusterPushSecrets }}
{{ include "library._crdResource" (dict
  "name"       $name
  "res"        $cps
  "kind"       "ClusterPushSecret"
  "apiVersion" "external-secrets.io/v1alpha1"
  "namespaced" false
  "context"    $) }}
{{- end }}
{{- end -}}
