{{/*
Render PushSecret CRs from .Values.eso.pushSecrets dict.
Namespace-scoped.

apiVersion: external-secrets.io/v1alpha1
ref: https://external-secrets.io/latest/api/pushsecret/
*/}}
{{- define "library.pushSecrets" -}}
{{- range $name, $ps := .Values.eso.pushSecrets }}
{{ include "library._crdResource" (dict
  "name"       $name
  "res"        $ps
  "kind"       "PushSecret"
  "apiVersion" "external-secrets.io/v1alpha1"
  "namespaced" true
  "context"    $) }}
{{- end }}
{{- end -}}
